;; This buffer is for notes you don't want to save, and for Lisp evaluation.
;; If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file's own buffer.

package:
  name: caiman
  version: "1.0"

source:
  git_url: https://github.com/flatironinstitute/CaImAn

requirements:
  build:
    - python
    - setuptools
    - cython

  run:
    - python
    - setuptools
    - future
    - numpy
    - scipy
    - ipython
    - ipyparallel
    - jupyter
    - matplotlib
    - scikit-image
    - scikit-learn
    - h5py
    - cython
    - spyder
    - nose
    - bokeh 
    - tqdm
    - opencv3=3.2.0 # [py27 or py35]
    - opencv3=3.1.0 # [py36]
    - pip:
      - tifffile
      - peakutils

test:
   requires:
      - nose
   commands:
      - nosetests
  
app:
  summary:  "Caiman: calcium imaging analysis"

about:
  home: https://github.com/flatironinstitute/CaImAn
  license: BSD
  license_file: LICENSE

